@startuml
skinparam packageStyle frame
package it.unisa.diem.dao as dao{
package interfacce {
interface DAO{}
interface AnalisiDAO{}
interface DocumentoDAO{}
interface DomandaDAO{}
interface StopwordDAO{}
interface UtenteDAO{}
}
package postgres{
class AnalisiDAOPostgres{}
class DocumentoDAOPostgres{}
class DomandaDAOPostgres{}
class StopwordDAOPostgres{}
class UtenteDAOPostgres{}
}
}

package it.unisa.diem.main as main{
class Main{}
package controller{
class SignUpViewController{}
class LogInViewController{}
class LoadViewController{}
class DifficultySelectionViewController{}
class HistoryViewController{}
class HomeMenuViewController{}
class ResultsViewController{}
class QuestionViewController{}
class LeaderBoardViewController{}
}
}
package it.unisa.diem.model.gestione as gestione{
package analisi{
    class Analisi {
        -Documento documento
        -Map<String, Integer> frequenzeTesto
        -Lingua linguaAnalisi
        -Difficolta difficoltaAnalisi
        -String titolo
        -StopwordManager stopwordAnalisi
        -String pathAnalisi

        +Analisi(Documento documento)
        +Documento getDocumento()
        +Map<String, Integer> getFrequenzeTesto()
        -List<String> getWordsDocument()
        +Map<String, Integer> frequenzeDocumento()
        +void caricaAnalisi()
        +static Analisi leggiAnalisi(Documento doc)
        -static String recuperaAnalisiPath(Documento doc)
        +String toString()
    }

class Documento {
        -String titolo
        -Lingua lingua
        -Difficolta difficolta
        -StopwordManager stopword
        -String path
        -List<String> testo

        +Documento(String titolo, Lingua lingua, Difficolta difficolta, StopwordManager stopword)
        +Documento()
        +String getTitolo()
        +Lingua getLingua()
        +StopwordManager getStopword()
        +String getPath()
        +void setPath(String path)
        +Difficolta getDifficolta()
        +List<String> getTesto()
        +void convertiTxtToBin(File inputFile)
        +static Documento leggiDocumento(String filename)
        -static void getAttributes(String filename, Documento dr)
        +String toString()
    }

class Stopword{}
Documento "1" --* "1" Analisi : contiene

}
package sessione{
class Domanda{}
class Sessione{}
}
package utenti{
class User{}
class Admin{}
}
}

package it.unisa.diem.utility as utility{
class SceneLoader{}
}
@enduml